export const films2026 = [
  { title: "Eclipse Protocol", imdbRating: 7.4, votes: 8421 },
  { title: "Neon Frontier", imdbRating: 6.9, votes: 932 },
  { title: "The Last Orbit", imdbRating: 8.1, votes: 15673 },
  { title: "Crimson Divide", imdbRating: 7.0, votes: 4812 },
  { title: "Quantum Harbor", imdbRating: 8.3, votes: 21345 },
  { title: "Glass Horizon", imdbRating: 6.8, votes: 774 },
  { title: "Shadow Meridian", imdbRating: 7.6, votes: 9876 },
  { title: "Frozen Anthem", imdbRating: 6.5, votes: 653 },
  { title: "Velvet Rebellion", imdbRating: 7.9, votes: 14321 },
  { title: "Silent Overdrive", imdbRating: 6.7, votes: 5342 },
  { title: "Ivory Skies", imdbRating: 7.2, votes: 2891 },
  { title: "The Ember Code", imdbRating: 8.0, votes: 17854 },
  { title: "Parallel Ashes", imdbRating: 6.6, votes: 712 },
  { title: "Midnight Helix", imdbRating: 7.5, votes: 9634 },
  { title: "Atlas Reborn", imdbRating: 8.4, votes: 25431 },
  { title: "Solar Drift", imdbRating: 7.1, votes: 3178 },
  { title: "The Copper Crown", imdbRating: 6.9, votes: 845 },
  { title: "Echoes of Titan", imdbRating: 8.2, votes: 19432 },
  { title: "Fractured Signal", imdbRating: 7.3, votes: 4231 },
  { title: "Obsidian Pact", imdbRating: 7.8, votes: 11234 },
  { title: "The Hollow Engine", imdbRating: 6.4, votes: 598 },
  { title: "Burning Aurora", imdbRating: 7.7, votes: 8675 },
  { title: "City of Lenses", imdbRating: 6.8, votes: 912 },
  { title: "Aetherfall", imdbRating: 8.5, votes: 30122 },
  { title: "Gravity's Wake", imdbRating: 7.0, votes: 3744 },
  { title: "The Marble Paradox", imdbRating: 7.4, votes: 6431 },
  { title: "Chrome Cathedral", imdbRating: 6.7, votes: 721 },
  { title: "Violet Dominion", imdbRating: 7.6, votes: 9987 },
  { title: "Deep Current", imdbRating: 6.9, votes: 856 },
  { title: "The Iron Bloom", imdbRating: 7.8, votes: 11023 },
  { title: "Nova Cartel", imdbRating: 6.6, votes: 689 },
  { title: "Paper Suns", imdbRating: 7.3, votes: 4188 },
  { title: "Starlight Dominion", imdbRating: 8.1, votes: 16542 },
  { title: "Broken Spectrum", imdbRating: 6.5, votes: 744 },
  { title: "Phantom Archive", imdbRating: 7.9, votes: 12311 },
  { title: "The Scarlet Index", imdbRating: 7.2, votes: 3321 },
  { title: "Digital Nomads", imdbRating: 6.8, votes: 887 },
  { title: "Lunar Divide", imdbRating: 8.0, votes: 14987 },
  { title: "Ashfall Symphony", imdbRating: 7.1, votes: 2865 },
  { title: "The Sapphire Vault", imdbRating: 6.7, votes: 654 },
  { title: "Echo Chamber X", imdbRating: 7.4, votes: 5210 },
  { title: "Titanium Rain", imdbRating: 8.3, votes: 20876 },
  { title: "Vanishing Point Zero", imdbRating: 6.9, votes: 911 },
  { title: "The Polar Frame", imdbRating: 7.5, votes: 8764 },
  { title: "Hollow Crown Rising", imdbRating: 7.8, votes: 11345 },
  { title: "Craterline", imdbRating: 6.6, votes: 578 },
  { title: "The Electric Orchard", imdbRating: 8.2, votes: 18234 },
  { title: "Infinite Harbor", imdbRating: 7.0, votes: 3476 },
  { title: "The Glass Directive", imdbRating: 7.6, votes: 9054 },
  { title: "Zenith Aftermath", imdbRating: 8.4, votes: 26781 }
];